### ISSUE TITLE
`Uncaught Error: Missing StyleRegistry`

### ISSUE THREAD

**Issue by trusktr** [LXSMNSYC/solid-styled#2]
I have an app that uses solid-app-router (maybe that has to do with it), and I get that error. Working on a repro...

**Comment by trusktr** [comment]
Repro: https://github.com/trusktr/solid-styled/tree/solid-styled-issue-2

Unfortunately this simple reproduction attempt doesn't yet reproduce the issue

To run, `"type": "module"` must be added to the babel plugin inside node_modules after npm install.

**Comment by trusktr** [comment]
repro not ready yet, hand on

**Comment by trusktr** [comment]
Repro ready

**Comment by trusktr** [comment]
steps to run:

```sh
git clone git@github.com:trusktr/solid-styled.git
cd solid-styled/
git checkout solid-styled-issue-2
npm i && npm run build
```

It will end with the error:

```
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
...
```

Then

- edit `node_modules/babel-plugin-solid-styled/package.json` and `node_modules/solid-styled/package.json` and add `"type": "module"` to both of them, 
- run `npm run build`

and now the build passes, but unfortunately this simple example doesn't yet reproduce the `Missing StyleRegistry` error.

**Comment by lxsmnsyc** [comment]
This should probably be solved now?
- solid-styled already ships with `"type": "module"`
- solid-styled's StyleRegistry is now optional

**Comment by lxsmnsyc** [comment]
Since there's lack of updates, and I positively believe this has been already fixed, I'll close this issue.
