### ISSUE TITLE
Doesn't seem to work with Solid Start's filesystem routes

### ISSUE THREAD

**Issue by X1nto** [LXSMNSYC/solid-styled#20]
So, I have a page in `src/routes/index.tsx`:
```tsx
export default function Home() {
  css`
    #container {
      width: 100%;
      display: flex;
      flex-direction: row;
      gap: 32px;
    }
    
    #sidebar {
      max-width: 100px;
    }
    
    #main {
      flex-grow: 1;
    }
  `
  return (
    <div id="container">
      <div id="sidebar">Hello this is sidebar</div>
      <div id="main">Hello this is main</div>
    </div>
  );
}
```
However, these styles are not getting applied to the website:
![image](https://github.com/lxsmnsyc/solid-styled/assets/48173186/22cc6386-9093-45dc-a34b-185c23e047ac)
![image](https://github.com/lxsmnsyc/solid-styled/assets/48173186/893466e4-7733-43a0-8007-6b86b77741f3)
There are no errors in the console, it just straight up refuses to work.
What's interesting, is that it seems to work inside the `src/root.tsx` file.

**Comment by lxsmnsyc** [comment]
What does `<head>` contain? Seems like compiler is working correctly

**Comment by X1nto** [comment]
> What does `<head>` contain? Seems like compiler is working correctly

Hm, it seems add styles
![image](https://github.com/lxsmnsyc/solid-styled/assets/48173186/a306f3a5-8c3d-4f64-a0e9-4f4a426032b7)

**Comment by X1nto** [comment]
As far as I understood, it didn't add the `s:c-Home-aa557f6b-0-1` thing to the `#container` div.

**Comment by lxsmnsyc** [comment]
Okay I do see it now. Can you make a repro of this?

**Comment by X1nto** [comment]
> Okay I do see it now. Can you make a repro of this?

Sure! I'll do it first thing in the morning.

**Comment by X1nto** [comment]
[repro.zip](https://github.com/lxsmnsyc/solid-styled/files/11523863/repro.zip)
@lxsmnsyc attached reproduction project, please see comments inside `routes/index.tsx` and `components/PageButton.tsx`.

**Comment by lxsmnsyc** [comment]
> [repro.zip](https://github.com/lxsmnsyc/solid-styled/files/11523863/repro.zip) @lxsmnsyc attached reproduction project, please see comments inside `routes/index.tsx` and `components/PageButton.tsx`.

Here's some of my comments
> ```js
>  //this also won't work if I replace `a` with `A`
>  return (
>    <a href={props.href}>
>      {props.children}
>    </a>
>  )
>  ```

[This is mentioned in the docs](https://github.com/lxsmnsyc/solid-styled#forward-scope)

For the index page, it's definitely weird that the JSX isn't getting transformed. I'm most likely thinking that it transforms before solid-styled goes through. I'm not sure what to do with this one hmmm

**Comment by lxsmnsyc** [comment]
![image](https://github.com/lxsmnsyc/solid-styled/assets/4783372/945e6634-d1a2-4633-973a-8de550340565)

Okay weird, seems like the pages are transformed first.

**Comment by lxsmnsyc** [comment]
@X1nto I've released 0.9.1, please check if it works

**Comment by X1nto** [comment]
> @X1nto I've released 0.9.1, please check if it works

Fixed with routes, but using `A` instead of `a` still doesn't work. Although since that is out of the scope of this issue, I'll be closing this one. If you want, I can open a separate issue regarding the `A` and `a` thing.

**Comment by X1nto** [comment]
> @X1nto I've released 0.9.1, please check if it works

Fixed with routes, but using `A` instead of `a` still doesn't work. Although since that is out of the scope of this issue, I'll be closing this one. If you want, I can open a separate issue regarding the `A` and `a` thing.

**Comment by lxsmnsyc** [comment]
@X1nto please read my other comment.

**Comment by X1nto** [comment]
> @X1nto please read my other comment.

Oh, sorry, didn't notice the comment 😄
